"""add guest fields to order

Revision ID: 1b79288e803e
Revises: db73f3f54427
Create Date: 2026-08-20 18:44:51.551860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b79288e803e'
down_revision = 'db73f3f54427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guest_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('guest_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('guest_phone')
        batch_op.drop_column('guest_email')
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
