"""add attachment_filename

Revision ID: 25f92ca316bc
Revises: 
Create Date: 2026-08-07 11:56:30.530808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25f92ca316bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('target_audience',
               existing_type=mysql.ENUM('all', 'new_user', 'inactive_30_days'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'all'"))
        batch_op.alter_column('placement_zone',
               existing_type=mysql.ENUM('hero_carousel', 'mid_feed', 'cart_upsell', 'top_bar'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'hero_carousel'"))
        batch_op.alter_column('display_style',
               existing_type=mysql.ENUM('cinematic_21_9', 'square_1_1', 'pill_text', 'story_circle', 'popup_modal'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'cinematic_21_9'"))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    with op.batch_alter_table('outlet_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlet_stocks_outlet_id'), ['outlet_id'], unique=False)

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_outlet_owner_id'))
        batch_op.create_foreign_key('fk_outlet_owner_id', 'users', ['owner_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('attachment_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('attachment_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('attachment_filename')

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_outlet_owner_id', type_='foreignkey')
        batch_op.create_index(batch_op.f('fk_outlet_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('outlet_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlet_stocks_outlet_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_type'))

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('display_style',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('cinematic_21_9', 'square_1_1', 'pill_text', 'story_circle', 'popup_modal'),
               existing_nullable=True,
               existing_server_default=sa.text("'cinematic_21_9'"))
        batch_op.alter_column('placement_zone',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('hero_carousel', 'mid_feed', 'cart_upsell', 'top_bar'),
               existing_nullable=True,
               existing_server_default=sa.text("'hero_carousel'"))
        batch_op.alter_column('target_audience',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('all', 'new_user', 'inactive_30_days'),
               existing_nullable=True,
               existing_server_default=sa.text("'all'"))
        batch_op.alter_column('image_url',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
