"""add description, eyebrow_text, button_text to banners

Revision ID: b7efb23b78ae
Revises: 9d094a9814ba
Create Date: 2026-08-19 22:01:44.847414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7efb23b78ae'
down_revision = '9d094a9814ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('eyebrow_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('button_text', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_column('button_text')
        batch_op.drop_column('eyebrow_text')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
