"""Add zero-trust schemas

Revision ID: cd7602c2b924
Revises: 25f92ca316bc
Create Date: 2026-08-17 13:20:22.633584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd7602c2b924'
down_revision = '25f92ca316bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_phone_number'))

    op.drop_table('whatsapp_messages')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_best_seller')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('refund_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue_cutoff_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfid_tag', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['rfid_tag'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rfid_tag')

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('revenue_cutoff_date')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('refund_reason')
        batch_op.drop_column('refund_amount')
        batch_op.drop_column('refund_status')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_best_seller', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))

    op.create_table('whatsapp_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('message_body', mysql.TEXT(), nullable=False),
    sa.Column('direction', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###
