"""Add new item info fields

Revision ID: db73f3f54427
Revises: b7efb23b78ae
Create Date: 2026-08-20 16:27:32.527057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db73f3f54427'
down_revision = 'b7efb23b78ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nutritional_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dietary_guidelines', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('dietary_guidelines')
        batch_op.drop_column('nutritional_info')
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
